ALTER TABLE clans
  ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS exp INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS money INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arm_id INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS tag_color TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS homepage TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS access INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS access_level INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS max_members INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS clans_tag_lower_unique
  ON clans (lower(tag))
  WHERE tag <> '';

ALTER TABLE clan_members
  ADD COLUMN IF NOT EXISTS member_level INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS money INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clan_exp INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exp_koef INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS player_exp INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS clan_invites (
  clan_id BIGINT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
  player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (clan_id, player_id)
);

CREATE TABLE IF NOT EXISTS clan_events (
  id BIGSERIAL PRIMARY KEY,
  clan_id BIGINT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
  event_type INTEGER NOT NULL DEFAULT 0,
  creator_player_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clan_events_clan_id_idx ON clan_events(clan_id, id DESC);

CREATE TABLE IF NOT EXISTS clan_treasury_events (
  id BIGSERIAL PRIMARY KEY,
  clan_id BIGINT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
  player_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
  player_name TEXT NOT NULL DEFAULT '',
  money INTEGER NOT NULL DEFAULT 0,
  event_type INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clan_treasury_events_clan_id_idx ON clan_treasury_events(clan_id, id DESC);

CREATE TABLE IF NOT EXISTS clan_inventory (
  clan_id BIGINT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
  item_key TEXT NOT NULL,
  item_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (clan_id, item_key)
);
