ALTER TABLE player_developer_effects
  ADD COLUMN IF NOT EXISTS spawn_level SMALLINT NOT NULL DEFAULT 1 CHECK (spawn_level BETWEEN 1 AND 3),
  ADD COLUMN IF NOT EXISTS death_level SMALLINT NOT NULL DEFAULT 1 CHECK (death_level BETWEEN 1 AND 3);
